### ISSUE TITLE
How to install ???

### ISSUE THREAD

**Issue by lbayle** [patrikx3/gitlist#33]
Hi,
I downloaded the latest release (gitlist-2021.4.102) but I realy don't understand how to get it to work.
all I get is the content of the directory displayed in my browser (obviously, there is no index.php)

Is there a simple package that I could install, setup config.ini and it works out of the box without any compose /curl / nmp stuff ?

thx

**Comment by lbayle** [comment]
Hi
thank you for your answer.
I'm not sure to understand your answer:
Should I rewrite this configuration script for apache (as I'm not using
nginx) ?
is there any documentation on how to do that ?

Best regards

Louis BAYLE
***@***.***

**Comment by lbayle** [comment]
Ok, nevermind, i'll look for some other option.
Thanks for your help

**Comment by SirHerpDerp** [comment]
I just stumpled upon this issue and may I can help you since I have installed this gitlist fork a week ago on an apache webserver on my Raspberry Pi.
first, take a look at the /public/ directory, there you will find your desired index.php.
Theres also a .htaccess which should be edited (according to installation instruction https://github.com/patrikx3/gitlist/blob/master/INSTALL.md), but this didn't work for me.

So here's what I've done.
Edited the /config.ini to my personal needs, don't forget to change the fourth line here.
`repositories[] = '/var/git/' ; Path to your repositories`

Afterwards I added a virtual host to my apache server (easiest way is to edit /etc/apache2/sites-enabled/000-default.conf). For example this could be added to the config. (**just an example, don't use this if there are other services/weboages on your webserver**)

```
<VirtualHost IP_ADDRESS_OF_WEBSERVER:80>
        DocumentRoot "/var/www/html/gitlist/public"
</VirtualHost>
```

In this case, everytime I try to connect to my Raspi via browser, it will redirect me automatically to the /public/ folder.
Or in my case, I added a DNS entry on my DNS server so that the domain 'repos.local' will redirect me to my Raspi and added the following to my apache config:

```
<VirtualHost *:80>
        DocumentRoot "/var/www/html/gitlist/public"
        ServerName repos.local
</VirtualHost>
```

So this will only redirect me if I enter repos.local to my browser.

Hope I could help you in any way. :-)
And don't forget to restart apache service after adding a virtual host :P
