### ISSUE TITLE
.htaccess file is missing from the releases

### ISSUE THREAD

**Issue by cedx** [patrikx3/gitlist#7]
I've download `gitlist-v1.0.3.zip`: no `.htaccess` file was in the archive.
I've tried with `gitlist-v1.0.4-rc.1.zip`: also no `.htaccess` file.

The `INSTALL.md` guide should provide the required Apache settings, or the `.htaccess` file should be packaged in the archives.

Thanks in advance.

**Comment by volomike** [comment]
This didn't help me. I downloaded the zip but don't understand what to do with it when I unzipped. I was looking for an .htaccess file but didn't see one in the root folder. I found one in public, but when I go to my website as https://example.com/gitlist, it points to the folder above public, and not the public folder. And when I go to https://example.com/gitlist/public, I get "Template "layout.twig" is not defined in "error.twig" at line 1" error.

So, backing up, here's what I did. I downloaded the latest stable version from here:

https://github.com/patrikx3/gitlist

I unloaded into /home/example/public_html/gitlist as an unzipped file.

I then ssh'd into my shared hosting cPanel server (over at A2 Hosting). I created the cache folder and gave it the proper permissions. I then did "composer install" and it began installing stuff. I renamed my config.example.ini to config.ini and edited it so that I pointed to my git folder and then added this for the clone button:

[clone_button]
show_ssh_remote = true
ssh_host = 'example.com'
ssh_url_subdir = '' 
ssh_port = '7822' 
ssh_user = 'example' 
ssh_user_dynamic = false
ssh_clone_subdir = ''

I then tried to connect to https://example.com/gitlist, but got the permissions error and when I checked the error log, it said it couldn't find an index.php. I then realized, oh, it must be needing to load from public. So, I didn't know the .htaccess trick to make that work, so I went to https://example.com/gitlist/public, and that's when I got the "Template "layout.twig" is not defined in "error.twig" at line 1" error.

**Comment by volomike** [comment]
Okay, I cleared one hurdle. This is the missing .htaccess file that one needs in the root of the gitlist folder in order for it to load the public folder.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```

However, this then led to Twig errors like I've mentioned. I'm going to file the Twig errors as a separate issue.
